---
- name: Setup LUKSO node
  hosts: lukso_node_1
  become: true

  # tasks:
  #   - name: Firewall rule - allow port 8302
  #     iptables:
  #       chain: INPUT
  #       destination_port: "8302"
  #       ctstate: NEW
  #       jump: ACCEPT
  #       protocol: tcp
