---
- name: Provision a new server with hardened SSH and basic iptables.

  # Specify the hosts you want to target
  # https://github.com/joelhans/ssdnodes-ansible-provision
  hosts: nodes
  remote_user: ubuntu
  become: true

  vars:
    username: hugo
    public_key: ~/.ssh/id_rsa.pub

  roles:
    # - user
    # - packages
    # - ssh
    # - iptables
    # - fail2ban
